//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueFPSBoost.Native.WMI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WinMgmtResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinMgmtResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeagueFPSBoost.Native.WMI.WinMgmtResources", typeof(WinMgmtResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /resetrepository.
        /// </summary>
        public static string ArgumentResetRepository {
            get {
                return ResourceManager.GetString("ArgumentResetRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /salvagerepository.
        /// </summary>
        public static string ArgumentSalvageRepository {
            get {
                return ResourceManager.GetString("ArgumentSalvageRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /verifyrepository.
        /// </summary>
        public static string ArgumentVerifyRepository {
            get {
                return ResourceManager.GetString("ArgumentVerifyRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to winmgmt.exe.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code:.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI Repository is consistent.
        /// </summary>
        public static string RepositoryConsistent {
            get {
                return ResourceManager.GetString("RepositoryConsistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI repository has been reset.
        /// </summary>
        public static string RepositoryResetted {
            get {
                return ResourceManager.GetString("RepositoryResetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WMI repository has been salvaged.
        /// </summary>
        public static string RepositorySalvaged {
            get {
                return ResourceManager.GetString("RepositorySalvaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winmgmt.
        /// </summary>
        public static string ServiceName {
            get {
                return ResourceManager.GetString("ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %Windir%\System32\wbem.
        /// </summary>
        public static string WorkingDirectory {
            get {
                return ResourceManager.GetString("WorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error code:  0x8007007E.
        /// </summary>
        public static string WOW64Error {
            get {
                return ResourceManager.GetString("WOW64Error", resourceCulture);
            }
        }
    }
}
