//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeagueFPSBoost.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class UpdaterMessageBoxSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static UpdaterMessageBoxSettings defaultInstance = ((UpdaterMessageBoxSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UpdaterMessageBoxSettings())));
        
        public static UpdaterMessageBoxSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ManuallyDownloadLeagueFPSBoostMessageBox_Ran {
            get {
                return ((bool)(this["ManuallyDownloadLeagueFPSBoostMessageBox_Ran"]));
            }
            set {
                this["ManuallyDownloadLeagueFPSBoostMessageBox_Ran"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FailedUpdateSorryMessageBox_Ran {
            get {
                return ((bool)(this["FailedUpdateSorryMessageBox_Ran"]));
            }
            set {
                this["FailedUpdateSorryMessageBox_Ran"] = value;
            }
        }
    }
}
